---
- hosts: all
  become: true

  tasks:
    - name: Set timezone to Asia/Bangkok
      community.general.timezone:
        name: Asia/Bangkok

    - name: Install required system packages
      apt:
        pkg:
          - open-iscsi
        state: latest
        update_cache: true

    - name: Add value /etc/default/grub
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=""'
        line: GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"

    - name: update-grub
      shell: update-grub

    - name: update-grub2
      shell: update-grub2
  
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
